### ISSUE TITLE
code and dataset

### ISSUE THREAD

**Issue by zhanghaoie** [Timothy023/RLMEC#1]
publish time?

**Comment by Timothy023** [comment]
Thank you for your interest in our work. Our code and data will be released within this week.

**Comment by LeiyanGithub** [comment]
When can the files corresponding to the script directory be seen？

**Comment by Timothy023** [comment]
Thanks for your interest. We have released our code and data about RLMEC.

**Comment by zhanghaoie** [comment]
Hi, could you also release some examples for train the grm model?

**Comment by Timothy023** [comment]
> Hi, could you also release some examples for train the grm model?

Here is an example about how to train the grm in qa tasks:

First, add the path to your reference model in the 22-th line of `process_data/Gen_Samples/scripts/run_inference_qa.sh`

Second, run this script to utilize the reference model to generate samples. The data can be found in `process_data/Gen_Samples/data/qa.jsonl`. It's ok to use your own data. The data contains multi-line of json and each json should contain the keywords: `problem`, `solution`, and `answer`.

Third, run `process_data/Minimum_Edit/scripts/run_miniedit_tm_qa.sh` to distill samples from the teacher model (Claude 2 in our code). You should set your API key at the 20-th line of `process_data/Minimum_Edit/miniedit_tm_qa.py`

Forth, run `train/scripts/run_train_grm.sh` to train the grm model. Do not forget to set your backbone model path at the 7-th line and your save path at the 11-th line of `train/scripts/run_train_grm.sh`.

After above four steps, you can get the well trained grm model.

Hope my answer can help you.
