### ISSUE TITLE
Question about the SFT method

### ISSUE THREAD

**Issue by YJiangcm** [Timothy023/RLMEC#3]
Thanks for your excellent work!

In Table 3 of your paper, I wonder what is the difference between "**SFT LLM**" and "**+ SFT**"?

![image](https://github.com/Timothy023/RLMEC/assets/70904956/d6d39913-c189-4066-84f8-ab6dac833ecd)

Looking forward to your reply.

**Comment by Timothy023** [comment]
Thanks for your interest in our work.

`+ SFT` denotes utilizing the SFT data to further fine-tune the `SFT LLM`.

Hope my answer can help you.

**Comment by YJiangcm** [comment]
Thanks for your reply. So the `SFT LLM` means llama2-7b-chat; `+ SFT` means further fine-tuning llama2-7b-chat using QA or math data; the below methods such as `+RFT`, `+DPO` mean further training based on llama2-7b-chat.

Is my understanding correct?

**Comment by Timothy023** [comment]
There might be some difference between your understanding and our experiment about the meaning of `SFT LLM`.

`SFT LLM` in QA task denotes using the mixture of the training set of ECQA and QASC (ie, `process_data/Gen_Samples/data/qa.jsonl`) to train llama2-7b to make it adapt to the QA task.

`+SFT`, `RFT` and `DPO` mean further training based on the `SFT LLM`, which is the same as your understanding.

Hope the answer can address your questions.

**Comment by YJiangcm** [comment]
Thanks. My last question is: since `SFT LLM` uses ECQA and QASC as the training data, then what is the training data of `+SFT`?

**Comment by Timothy023** [comment]
Also the training set of ECQA and QASC.
